### ISSUE TITLE
[15.0] Traceback when assigning type on partner

### ISSUE THREAD

**Issue by tarbib** [Smile-SA/odoo_addons#111]
Steps to reproduce :
Create partner
Choose a type
Click on save 

_RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
....

Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
RecursionError: maximum recursion depth exceeded while calling a Python object_

**Comment by tarbib** [comment]
[Full error](https://pastebin.com/c60WhwFW)
