### ISSUE TITLE
[MIG] smile_data_integration

### ISSUE THREAD

**Issue by C2dricLeroy** [Smile-SA/odoo_addons#124]
Hello there, 

I'm working on a migration from Odoo v13 to Odoo v17.

When I gave my db dump to Odoo services via 
```python <(curl -s https://upgrade.odoo.com/upgrade) test -d <your db name> -t <target version>``` (see [On-premise](https://www.odoo.com/documentation/17.0/administration/upgrade.html))
I encountered an error. 

It seems that the **old_id** field added by **smile_data_integration** cannot be deleted by  Odoo migration scripts.

Below is the relevant part of the error : 
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 505, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/tmp/tmpod73xd_d/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 108, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_model.py", line 2328, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/14.0/addons/website/models/ir_model_data.py", line 36, in _process_end_unlink_record
    return super()._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_model.py", line 2251, in _process_end_unlink_record
    record.unlink()
  File "/tmp/tmpod73xd_d/migrations/base/0.0.0/pre-models-ir_model.py", line 207, in unlink
    raise util.MigrationError(message)
odoo.upgrade.util.exceptions.UpgradeError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: helpdesk.sla.old_id
2024-08-13 07:08:04,480 26 INFO db_1880384 odoo.service.server: Initiating shutdown 
2024-08-13 07:08:04,480 26 INFO db_1880384 odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-08-13 07:08:04,481 26 INFO db_1880384 odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 9 connections  
[ERROR]::Error during the upgrade: command execution has failed with the error code 255
2024-08-13 09:08:16 ERROR: The upgrade request has failed
```

Has anyone ever encountered this kind of error?
Thanks in advance,

**Comment by C2dricLeroy** [comment]
The solution for our project was to delete the old_id as it was unused. I close this issue
