### ISSUE TITLE
[8.0] Ignored tests in smile_ci

### ISSUE THREAD

**Issue by isabellerichard** [Smile-SA/odoo_addons#4]
Text field ignored_tests of model scm.repository.branch is wrong parsed:

```
Traceback (most recent call last):
File "/usr/src/odoo/server/openerp/service/wsgi_server.py", line 75, in xmlrpc_return
result = openerp.http.dispatch_rpc(service, method, params)
File "/usr/src/odoo/server/openerp/http.py", line 100, in dispatch_rpc
result = dispatch(method, params)
File "/usr/src/odoo/ci-addons/smile_test/service/test.py", line 249, in new_dispatch
return run_tests(*params)
File "/usr/src/odoo/ci-addons/smile_test/service/test.py", line 230, in run_tests
ignore = eval(tools.config.get('ignored_tests') or '{}')
File "<string>", line 1
{'my_module': 'all',
^
SyntaxError: unexpected EOF while parsing
```

**Comment by isabellerichard** [comment]
Constraint added on ignored_tests in commit 9234b53ed5fd5ade22bdbe3681fa063ead12412f
