### ISSUE TITLE
smile_web_auto_refresh javascript error with studio enabled

### ISSUE THREAD

**Issue by arosboro** [Smile-SA/odoo_addons#53]
I get an odoo dialog on any page reload with the following when I install the studio add on and smile_web_auto_refresh is configured for crm.lead create/write on the pipeline kanban view.

```
Uncaught TypeError: Cannot read property 'then' of undefined
http://localhost:8069/web/content/451-aca3411/web_studio.assets.js:100
Traceback:
TypeError: Cannot read property 'then' of undefined
    at Class.show_application (http://localhost:8069/web/content/451-aca3411/web_studio.assets.js:100:318)
    at Class.show_application (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:3541:371)
    at Array.<anonymous> (http://localhost:8069/web/content/569-5e9934c/web.assets_backend.js:556:2810)
    at Array.<anonymous> (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:801:198)
    at Array.deferred.<computed> (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:803:56)
    at fire (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:797:467)
    at Object.<anonymous> (http://localhost:8069/web/content/425-f7520f6/web.assets_common.js:802:772)
```

The actual js file affected is: `/web_studio/static/src/js/web_client.js`
and the function with the error is here:
```
show_application: function() {
            var self = this;
            return this._super.apply(this, arguments).then(function() {
                var qs = $.deparam.querystring();
                self.studioMode = _.contains(['main', 'app_creator'], qs.studio) ? qs.studio : false;
                if (self.studioMode) {
                    self._updateContext();
                    return self._openStudio();
                }
            });
        },
```

The first return statement is where this._super.apply(this, arguments) is undefined.

**Comment by vidimeylan** [comment]
Open file addons/smile_web_auto_refresh/static/src/js/web_auto_refresh.js , and look for "show_application" function (on line 13).

```javascript 
show_application: function() {
    this._super();
    this.start_polling();
},
```

modify this function to be like this :

```javascript 
show_application: function() {
    var res = this._super();
    this.start_polling();
    return res;
},
```

hopefully this gone work for you

**Comment by arosboro** [comment]
@vidimeylan Yes this resolved the error.  Thanks for the fast response and solution.

**Comment by isabellerichard** [comment]
Thanks for your quick solution, we will apply it to the module.

**Comment by fredanergi00** [comment]
Uncaught TypeError: this._super is not a function
could tell me,, why this error?
