### ISSUE TITLE
[10.0] smile_docker not working

### ISSUE THREAD

**Issue by R2GTX** [Smile-SA/odoo_addons#54]
Hello,

I got this error when i try to install the module smile_docker, thank you

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_perf_analyzer/models/http.py", line 23, in __call__
    res = profile(native_call)(self, *args, **kwargs)
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_perf_analyzer/tools/decorators.py", line 21, in wrapper
    return func(*args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_data_integration/models/models.py", line 133, in call_kw_multi
    return native_call_kw_multi(method, self, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 528, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_upgrade/models/registry.py", line 44, in new
    return native_new(db_name, force_demo, update_module=update_module)
  File "/opt/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 335, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_docker/models/docker_registry.py", line 103, in create
    registry.start_container()
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_docker/models/docker_container.py", line 81, in start_container
    if not container.is_alive(all=True):
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_docker/models/docker_container.py", line 39, in is_alive
    all=all, filters={'name': self.docker_container}))
  File "/home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_docker/models/docker_host.py", line 170, in get_containers
    containers.extend(docker_host.client.containers(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 210, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ParseError: "Connection aborted.
13
Permission denied" while parsing /home/leon/PycharmProjects/odoo/odoo_addons-10.0/smile_docker/data/docker_registry.xml:5, near
<record id="defaut_docker_registry" model="docker.registry">
            <field name="name">Registry</field>
            <field name="configfile" type="base64" file="smile_docker/data/registry_config.yml"/>
            <field name="docker_host_id" ref="defaut_docker_host"/>
        </record>
```

**Comment by isabellerichard** [comment]
Hi R2GTX, 

Is there a Docker server running locally, where you try to install your module?

**Comment by R2GTX** [comment]
Hi Isabelle,

Thank you for your response, yes there is a Docker server running locally. I manged to install the module smile_docker by running odoo server by root. I think i didn't have right on some file by running by odoo user.

**Comment by isabellerichard** [comment]
Hi R2GTX,

You probably should add odoo user to `docker` group, as explained [on Docker documentation](https://docs.docker.com/install/linux/linux-postinstall/).

**Comment by R2GTX** [comment]
Hi Isabelle,

Thank you for your quick response, yes it worked. Thank you again
