### ISSUE TITLE
smile_audit raise error when installing on Odoo 13 version

### ISSUE THREAD

**Issue by maksymkv25** [Smile-SA/odoo_addons#67]
Hello,

can't install on the new Odoo 13 version. Can you please fix it?

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1242, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1230, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 397, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 316, in init_models
    model.init()
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 846, in deco
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_config_parameter.py", line 50, in init
    params = self.sudo().search([('key', '=', key)])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1556, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4280, in _search
    self._flush_search(args, order=order)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4258, in _flush_search
    self.env[model_name].flush(field_names)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5233, in flush
    self.recompute(fnames, records=records)
TypeError: recompute() got an unexpected keyword argument 'records'
```

**Comment by isabellerichard** [comment]
Hello @maksymkv25 , the module has not yet been migrated to Odoo 13.0. We plan to migrate it in a few weeks. I invite you to check branch 13.0 later, or to submit a pull request.

Regards,

Isabelle

**Comment by maksymkv25** [comment]
Thank you

**Comment by adam314315** [comment]
Hi,

Any update on this issue?
