### ISSUE TITLE
can't access users after uninstall 

### ISSUE THREAD

**Issue by autoparts-tech** [Smile-SA/odoo_addons#71]
after uninstalling smile_access_control module if i want to dispaly users from setting i get this error 
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 904, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/odoo/odoo-server/odoo/models.py", line 4578, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo/odoo-server/odoo/models.py", line 1561, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/odoo-server/odoo/addons/base/models/res_users.py", line 467, in _search
    access_rights_uid=access_rights_uid)
  File "/odoo/odoo-server/odoo/models.py", line 4110, in _search
    query = self._where_calc(args)
  File "/odoo/odoo-server/odoo/models.py", line 3902, in _where_calc
    e = expression.expression(domain, self)
  File "/odoo/odoo-server/odoo/osv/expression.py", line 672, in __init__
    self.parse()
  File "/odoo/odoo-server/odoo/osv/expression.py", line 853, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'is_user_profile' in leaf "<osv.ExtendedLeaf: ('is_user_profile', '=', False) on res_users (ctx: )>"

**Comment by isabellerichard** [comment]
Hi,

I just commited for Odoo 13.0 an uninstall_hook to avoid the error on future installations. See https://github.com/Smile-SA/odoo_addons/commit/6d9c953c42bad6da9300d0392479776d255cf1fc

To fix error on your existing database, please go to act windows menu and empty field `domain` of the action `base.action_res_users`.
