### ISSUE TITLE
this.wysiwyg.saveCroppedImages error (Odoo 13 / smile_access_control)

### ISSUE THREAD

**Issue by nekopep** [Smile-SA/odoo_addons#74]
I've installed odoo CE 13 nightly build 20200228
and your plugin smile_access_control 13.0.1.0

sadly when I try to add a user profile:
I just set a profile name and click on save and get this javascript error on debian 10.2
- firefox ESR 68.5.0esr (64 bits)
- chromium: Version 79.0.3945.130 (Developer Build) built on Debian 10.2, running on Debian 10.3 (64-bit))

RRetraçage :
TypeError: this.wysiwyg.saveCroppedImages is not a function
    at Class.commitChanges (https://odoo.neko-labs.home/web/content/4844-b94610e/web.assets_backend.js:2581:55)
    at Class.prototype.<computed> (https://odoo.neko-labs.home/web/content/4827-9ce60e3/web.assets_common.js:3866:488)
    at Class.commitChanges (https://odoo.neko-labs.home/web/content/4844-b94610e/web.assets_backend.js:2635:13)
    at Class.commitChanges (https://odoo.neko-labs.home/web/content/4827-9ce60e3/web.assets_common.js:3869:371)
    at https://odoo.neko-labs.home/web/content/4844-b94610e/web.assets_backend.js:1384:235
    at Function._.map._.collect (https://odoo.neko-labs.home/web/content/4827-9ce60e3/web.assets_common.js:115:270)
    at Class.commitChanges (https://odoo.neko-labs.home/web/content/4844-b94610e/web.assets_backend.js:1384:169)
    at https://odoo.neko-labs.home/web/content/4844-b94610e/web.assets_backend.js:1367:355

Do i miss something?

**Comment by nekopep** [comment]
I've created a new database and do not have anymore the issue.
I close the issue.

**Comment by MochSM** [comment]
This because custom modules that use HTML editor, if you face error like that simply upgrade your custom modules.

**Comment by a0c** [comment]
Upgrading custom modules didn't solve it for me, so I had to delete auto-generated JS/CSS/JS.MAP assets from Attahments (`ir_attachments`) as described [here](https://github.com/odoo/odoo/issues/93675#issuecomment-1182604986). The assets were regenerated on next access (just browse Odoo from web) and the error was gone.

**Comment by MochSM** [comment]
@a0c this solution should not work anymore for newer versions.

**Comment by hassannnasir** [comment]
> @a0c this solution should not work anymore for newer versions.
Can you please share a solution if there's any for this error.
