### ISSUE TITLE
Odoo 13 Record does not exist or has been deleted. (Record: mail.mail(786,), User: 2)

### ISSUE THREAD

**Issue by rpgresearch** [Smile-SA/odoo_addons#76]
Try to create new User Profile and upon trying to click on "Users" or click save instead, receive error:
"Record does not exist or has been deleted.
(Record: mail.mail(786,), User: 2)"

Steps:
Go to Settings > Users & Companies > User Profiles
Click Create button.
Notice that in right hand corner for some reason over the image box is big read "Archived" diagonal banner.
Fill in new profile name and new email address.
Click either Save on left side of page, or "Users" on right side of page (currently listing 0).
Receive the error.
Cannot proceed.

Please advise.

**Comment by rpgresearch** [comment]
Here is screenshot of the create new profile page for some reason "Archived". Any ideas why this is happening?  
![odoo-smile-access-control-create-user-profile-archived-cant-create-new-profile-screenshot](https://user-images.githubusercontent.com/3338987/81571583-009dc980-9357-11ea-92b3-3b4ce80f2bf8.png)

**Comment by rpgresearch** [comment]
Error screenshot.
![odoo-smile-access-control-create-user-profile-archived-cant-create-new-profile-error-screenshot](https://user-images.githubusercontent.com/3338987/81571857-570b0800-9357-11ea-84d3-dd97116d57cc.png)

**Comment by rpgresearch** [comment]
Output from /var/log/odoo/odoo.log when click the Create Profile button:

2020-05-11 14:18:14,615 14080 INFO odoodb1 werkzeug: 96.79.202.21 - - [11/May/2020 14:18:14] "POST /web/dataset/call_kw/res.users/default_get HTTP/1.0" 200 - 38 0.021 0.019
2020-05-11 14:18:14,660 14080 INFO odoodb1 werkzeug: 96.79.202.21 - - [11/May/2020 14:18:14] "POST /web/dataset/call_kw/res.company/read HTTP/1.0" 200 - 2 0.002 0.011
2020-05-11 14:18:14,663 14075 INFO odoodb1 werkzeug: 96.79.202.21 - - [11/May/2020 14:18:14] "POST /web/dataset/call_kw/ir.model.fields/read HTTP/1.0" 200 - 3 0.003 0.012
2020-05-11 14:18:14,702 14075 INFO odoodb1 werkzeug: 96.79.202.21 - - [11/May/2020 14:18:14] "POST /web/dataset/call_kw/res.users/onchange HTTP/1.0" 200 - 1 0.001 0.009
2020-05-11 14:18:14,739 14075 INFO odoodb1 werkzeug: 96.79.202.21 - - [11/May/2020 14:18:14] "POST /web/dataset/call_kw/res.company/name_get HTTP/1.0" 200 - 2 0.004 0.014




Log output when click the Save button and error message pops up:

2020-05-11 14:19:15,229 14072 INFO odoodb1 odoo.addons.mail.models.mail_mail: Mail with ID 21363 and Message-Id '<224384601879023.1589206753.453792095184326-openerp-188-res.users@rpgrhip1-PRODUCTION>' successfully sent
2020-05-11 14:19:15,245 14072 INFO odoodb1 odoo.models.unlink: User #2 deleted mail.mail records with IDs: [21363]
2020-05-11 14:19:15,256 14072 ERROR odoodb1 odoo.addons.mail.models.mail_mail: failed sending mail (id: 21363) due to You cannot delete messages!
None
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_mail.py", line 383, in _send
    mail._postprocess_sent_message(success_pids=success_pids, failure_type=failure_type)
  File "/usr/lib/python3/dist-packages/odoo/addons/mass_mailing/models/mail_mail.py", line 103, in _postprocess_sent_message
    return super(MailMail, self)._postprocess_sent_message(success_pids, failure_reason=failure_reason, failure_type=failure_type)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_mail.py", line 174, in _postprocess_sent_message
    self.browse(mail_to_delete_ids).sudo().unlink()
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_mail.py", line 84, in unlink
    self.env['mail.message'].browse(mail_msg_cascade_ids).unlink()
  File "/opt/odoo/odoo13/addons/prt_mail_messages/models/prt_mail.py", line 431, in unlink
    self.unlink_rights_check()
  File "/opt/odoo/odoo13/addons/prt_mail_messages/models/prt_mail.py", line 365, in unlink_rights_check
    raise AccessError(_("You cannot delete messages!"))
odoo.exceptions.AccessError: ('You cannot delete messages!', None)
2020-05-11 14:19:15,308 14072 WARNING odoodb1 odoo.http: ('Record does not exist or has been deleted.\n(Record: mail.mail(21363,), User: 2)', None)
2020-05-11 14:19:15,312 14072 INFO odoodb1 werkzeug: 96.79.202.21 - - [11/May/2020 14:19:15] "POST /web/dataset/call_kw/res.users/create HTTP/1.0" 200 - 122 0.086 1.955



Suggestions please?

**Comment by rpgresearch** [comment]
I am logged in as the full default Odoo administrator when running this. No idea why it says "you cannot delete messages".
